version: "3"
services:
    api:
        image: fooapi-console
        container_name: fooapi-console
        build:
            context: ./src
            dockerfile: ./Dockerfile
        ports:    
            - "5001:80"     
        networks:
            - apinet
    wrk:
        image: skandyla/wrk
        container_name: wrk-console
        depends_on:
            - api
        networks:
            - apinet
        volumes:
            - ./out:/out
        entrypoint: /out/entrypoint.sh /usr/local/bin/wrk -t12 -c400 -d20s --latency http://api/weatherforecast
networks:
    apinet:   