version: "3"
services:
    api:
        image: fooapi-serilog
        container_name: fooapi-serilog
        build:
            context: ./src
            dockerfile: ./Dockerfile
        ports:    
            - "5001:80"     
        networks:
            - apinet    
    wrk:
        image: skandyla/wrk
        container_name: wrk-serilog
        depends_on:
            - api
        networks:
            - apinet
        volumes:
            - ./out:/out
        entrypoint: /out/entrypoint.sh /usr/local/bin/wrk -t12 -c400 -d20s --latency http://api/weatherforecast
networks:
    apinet:   