version: '3.2'

services:  
  api:
    image: fooapi-logstash
    container_name: fooapi-logstash
    build:
        context: ./src
        dockerfile: ./Dockerfile
    ports:    
        - "5001:80"     
    networks:
        - elk
  wrk:
    image: skandyla/wrk
    container_name: wrk-logstash
    depends_on:
        - api
    networks:
        - elk
    volumes:
        - ./out:/out
    entrypoint: /out/entrypoint.sh /usr/local/bin/wrk -t12 -c400 -d20s --latency http://api/weatherforecast


networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
